name: ssl-gcn
channels:
- conda-forge
dependencies:
- python=3.7.3
- scikit-learn=0.23.2
- scipy=1.6.2
- pandas=1.2.3
- numpy=1.19.2
- openpyxl=3.0.7
- xgboost=1.3.3
- joblib=1.0.1
- rdkit=2020.09.1

